
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Joao.Antonio\Desktop\Projekte\task_handler\build\build\assets\frame9")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("797x432")
window.configure(bg = "#F6FFF8")


canvas = Canvas(
    window,
    bg = "#F6FFF8",
    height = 432,
    width = 797,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    32.0,
    116.0,
    243.0,
    190.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    32.0,
    222.0,
    484.0,
    296.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    273.0,
    116.0,
    484.0,
    190.0,
    fill="#000000",
    outline="")

canvas.create_text(
    104.0,
    59.0,
    anchor="nw",
    text="Benutzerdaten ändern",
    fill="#6B9080",
    font=("Montserrat Bold", 26 * -1)
)

canvas.create_text(
    549.0,
    59.0,
    anchor="nw",
    text="Funktionen",
    fill="#6B9080",
    font=("Montserrat Bold", 26 * -1)
)

canvas.create_rectangle(
    515.0,
    59.0,
    517.0,
    370.0,
    fill="#CCE3DE",
    outline="")

canvas.create_rectangle(
    547.0,
    116.0,
    756.0,
    190.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
