
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Joao.Antonio\Desktop\Projekte\task_handler\build\build\assets\frame6")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("797x432")
window.configure(bg = "#F6FFF8")


canvas = Canvas(
    window,
    bg = "#F6FFF8",
    height = 432,
    width = 797,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    40.0,
    14.0,
    742.0,
    16.0,
    fill="#CCE3DE",
    outline="")

canvas.create_text(
    116.0,
    33.0,
    anchor="nw",
    text="Update ‘Aufgabe 002’",
    fill="#6B9080",
    font=("Montserrat Bold", 26 * -1)
)

canvas.create_text(
    116.0,
    65.0,
    anchor="nw",
    text="Change Details",
    fill="#6B9080",
    font=("Montserrat SemiBold", 16 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=40.0,
    y=33.0,
    width=53.0,
    height=53.0
)

canvas.create_rectangle(
    40.0,
    133.0,
    373.0,
    207.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    40.0,
    239.0,
    373.0,
    313.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    425.0,
    133.0,
    742.0,
    207.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    425.0,
    241.0,
    742.0,
    315.0,
    fill="#000000",
    outline="")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=326.0,
    y=339.0,
    width=144.0,
    height=48.0
)
window.resizable(False, False)
window.mainloop()
