
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Joao.Antonio\Desktop\Neuer Ordner\Neuer Ordner\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1200x680")
window.configure(bg = "#6B9080")


canvas = Canvas(
    window,
    bg = "#6B9080",
    height = 680,
    width = 1200,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    215.0,
    0.0,
    1200.0,
    680.0,
    fill="#F6FFF8",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=633.0,
    y=573.0,
    width=146.0,
    height=48.0
)

canvas.create_rectangle(
    317.0,
    108.0,
    1094.0,
    514.0,
    fill="#CCE3DE",
    outline="")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=8.0,
    y=141.0,
    width=183.0,
    height=32.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=8.0,
    y=188.0,
    width=180.0,
    height=32.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=8.0,
    y=387.0,
    width=180.0,
    height=226.0
)

canvas.create_text(
    255.0,
    33.0,
    anchor="nw",
    text="Dashboard",
    fill="#6B9080",
    font=("Montserrat Bold", 26 * -1)
)

canvas.create_rectangle(
    60.0,
    18.0,
    150.0,
    108.0,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
