
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Joao.Antonio\Desktop\Neuer Ordner\Neuer Ordner\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1151x624")
window.configure(bg = "#F6FFF8")


canvas = Canvas(
    window,
    bg = "#F6FFF8",
    height = 624,
    width = 1151,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    181.0,
    312.0,
    1028.0,
    419.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    181.0,
    139.0,
    1027.999755859375,
    245.888916015625,
    fill="#000000",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=481.0,
    y=519.0,
    width=190.0,
    height=48.0
)

canvas.create_text(
    181.0,
    58.0,
    anchor="nw",
    text="Task hinzufügen",
    fill="#6B9080",
    font=("Montserrat Bold", 26 * -1)
)
window.resizable(False, False)
window.mainloop()
